<input type="hidden" name="<?php echo $this->getNamePrefix(); ?>" value="" />
<ul class="checkboxes">
    <?php foreach ($this->getValues() as $name => $label): ?>
        <li>
            <input type="checkbox"
                   value="<?php echo $name?>"
                   name="<?php echo $this->getNamePrefix() ?>[]"
                   id="<?php echo $this->getHtmlId() . '_' . $name ?>"
                <?php echo ($this->isChecked($name) ? ' checked="checked"' : '') ?>
                <?php echo ($this->isDisabled() ? ' disabled="disabled"' : '') ?>
            />
            <label for="<?php echo $this->getHtmlId() . '_' . $name ?>">
                <?php echo $label ?>
            </label>
        </li>
    <?php endforeach;?>
</ul>